CFLAGS      := -Wall -fPIC -D_REENTRANT -pthread -D_XOPEN_SOURCE -D_GNU_SOURCE
LIB         := 
INC         := -I$(INCDIR)
INCDEP      := $(INC)

ifeq ($(TEST),1)
CFLAGS += -D_DB_TEST_VERSION
endif

ifeq ($(DEBUG),1)
CFLAGS += -ggdb -O0 -D_GODB_DEBUG
TARGET := $(TARGET)Debug
else
CFLAGS += -g -O2 -Werror
endif

ifeq ($(GPROF),1)
CFLAGS += -pg
endif

ifeq ($(DISABLE_MYSQL),1)
CFLAGS += -D_DISABLE_MYSQL
else
LIB += -lmysqlclient
ENABLE_MYSQLHELPER := 1
endif

ifeq ($(DISABLE_POSTGRES),1)
CFLAGS += -D_DISABLE_POSTGRES
else
LIB += -lpq
ENABLE_POSTGRESHELPER := 1
endif

ifeq ($(DISABLE_DBI),1)
CFLAGS += -D_DISABLE_DBI
else
LIB += -ldbi
ENABLE_POSTGRESHELPER := 1
ENABLE_MYSQLHELPER := 1
endif

ifeq ($(ENABLE_POSTGRESHELPER),1)
CFLAGS += -D_ENABLE_POSTGRESHELPER
endif

ifeq ($(ENABLE_MYSQLHELPER),1)
CFLAGS += -D_ENABLE_MYSQLHELPER
endif